---
title: "quartodoc"
format: html
editor: visual
---

GitHub REPO: <https://github.com/marcelotmiller/ENVS-193DS_spring-2025_final.git>

```{r}
library(tidyverse)
library(flextable)
library(gt)
library(janitor)
library(MuMIn)
library(scales)
library(here)
library(dplyr)
library(readr)
```

\[#1\]

a.)

In part 1, based on wording including correlation and the use of continuous predictor and response variables, we know that a correlation test was used. The most likely test is a Pearson correlation coefficient, which was used to gauge the strength and direction of the proposed linear relationship between the distance from headwater (km) and the annual total nitrogen load (kg yr\^-1).

I part 2, we can assume that an ANOVA test was run to test for significant differences in average nitrogen load (kg yr\^-1) over multiple predictor variables. Other than being a multivariable, we can conclude that an ANOVA test was used because of the specific wording of having no difference in average, and the use of a p-value.

b.)

In addition to mentioning the test type, incorporating a post-hoc comparison, like Turkey's HSD, would specify which predictor variables had significant differences in nitrogen load. Doing so would offer more insight to which predictor variables are worth noting, rather than leaving the ANOVA p-value result of 0.02 left up to the bare interpretation that at least one group differs.

Another detail that can enhance the results is to include an effect size. Including an effect size estimate, such as an eta-squared for the ANOVA test, would help interpreters understand how large the differences that were deemed significant are, and whether the results are to be considered meaningful in actual practice.

c.)

Part 1;

Biological narrative: Nitrogen load trends towards an increase as the distance from the headwater increases, suggesting an ongoing accumulation of nitrogen as it travels downstream.

Statistical summary: A significant positive relationship between the distance from headwater (km) and total annual nitrogen load (kg) was found (test= Pearson correlation, r = (), p= 0.03, alpha= 0.05, df= ().)

Part 2:

Biological narrative: Nitrogen loads are seen to vary across several sources, with specific variables contributing more to the nitrogen accumulation in the San Joaquin River Delta than others. Such findings reveal that there is a disproportionate level of land use contributing to nitrogen pollution in proximity to the watershed.

Statistical summary:

A significant difference in mean annual nitrogen load (kg yr\^-1) between nitrogen source categories (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) (test = one-way ANOVA, F=(), p= 0.02, alpha= 0.05, df= ()). Post-hoc comparisons reveal that \_ sites are those that differ significantly, corresponding to \_..., effect sizes which show the level of influence.

#2
